### ISSUE TITLE
Feasibility of using official openwrt firmware with seeed mini-router

### ISSUE THREAD

**Issue by sergey-brutsky** [Seeed-Studio/seeed-linux-openwrt#21]
Hello,

I've bought [this mini-router](https://www.seeedstudio.com/Dual-GbE-Carrier-Board-with-4GB-RAM-32GB-eMMC-RPi-CM4-Case-p-5029.html).
[This page](https://wiki.seeedstudio.com/OpenWrt-Getting-Started/#flash-openwrt-image) claims that if you'd like to use another release of openwrt firmware I have to use [custom pre-built openwrt versions](https://1drv.ms/u/s!AqG2uRmVUhlSh0NHMLMmQKLyASvi?e=mup3cd).

Questions:

1) May I use [official openwrt firmwares](https://openwrt.org/toh/raspberry_pi_foundation/raspberry_pi) for devices based on raspberry pi 4 ? For example [rpi-4-ext4-factory.img.gz](https://downloads.openwrt.org/releases/21.02.1/targets/bcm27xx/bcm2711/openwrt-21.02.1-bcm27xx-bcm2711-rpi-4-ext4-factory.img.gz) for device I mentioned above ? 
My concern is that official firmwares may "brick" my device, is this correct ?

2) [This page claims](https://openwrt.org/toh/raspberry_pi_foundation/raspberry_pi#how_to_flash_openwrt_to_an_sd_card) that it is possible to flash firmware to sdcard, then plug-in sdcard to the device and raspberry pi will use this firmware during the boot stage rather then firmware from built-in emmc storage. Could you please clarify if this feature is working with seeed based devices ?

Thanks

**Comment by lakshanthad** [comment]
Hello,

To answer your questions.

1. We recommend you use our OpenWrt image because, it includes the necessary drivers and also easier getting started process
2. If you are using the CM4 eMMC version on the board, you cannot use SD cards. This is because the eMMC is internally connected to the SD card interface. It is also mentioned in the [official Raspberry Pi documentation](https://www.raspberrypi.com/documentation/computers/compute-module.html). You can check the section **Flashing the Compute Module eMMC** in the above document and it mentions there. When you flash OS to SD card, it won’t boot from the SD card because it will only prioritize the eMMC and only boot from eMMC.
However, if you want to boot the OS from an SD card, you need to use a CM4 module without the eMMC onboard. This way the board will directly boot from SD card.

**Comment by sergey-brutsky** [comment]
Does it mean that this [seeed router](https://www.seeedstudio.com/Dual-GbE-Carrier-Board-with-4GB-RAM-32GB-eMMC-RPi-CM4-Case-p-5029.html) doesn't support boot from sdcard ?

**Comment by lakshanthad** [comment]
If you use it as it is with the eMMC CM4, sd card boot is not supported. Only with non-eMMC CM4, sd card boot is supported.

**Comment by sergey-brutsky** [comment]
Got it. Thanks for quick responses :)

**Comment by wulfy23** [comment]
https://github.com/openwrt/openwrt/pull/4191
